%%{init: {"theme":"base","themeCSS":".nodeLabel,.edgeLabel,.cluster-label,.label{font-family:Arial,sans-serif!important;font-weight:bold!important;}","flowchart":{"htmlLabels":true,"curve":"linear","nodeSpacing":80,"rankSpacing":95,"padding":18},"themeVariables":{"fontFamily":"Arial, sans-serif","fontSize":"22px","primaryColor":"#fff","primaryTextColor":"#000","primaryBorderColor":"#000","lineColor":"#000","secondaryColor":"#fff","tertiaryColor":"#fff","edgeLabelBackground":"#fff","clusterBkg":"#fff","clusterBorder":"#000"}}}%%
flowchart LR
  EE_Issuer[EE-01<br/>Issuer]

  subgraph TB_Verifier["TB-03 Verifier agent control"]
    PO_VerifierAgent(PO-03<br/>Verifier agent)
  end

  EE_Verifier[EE-03<br/>Verifier]

  EE_Holder[EE-02<br/>Holder / Subject]

  subgraph TB_Holder["TB-02 Holder control"]
    direction LR
    PO_Browser(PO-02<br/>Browser /<br/>user agent)
    PO_Wallet(PO-04<br/>Wallet /<br/>Credential App)
    DS_CredentialRepo[(DS-01<br/>Wallet Storage)]
  end

  subgraph TB_Issuer["TB-01 Issuer agent control"]
    PO_IssuerAgent(PO-01<br/>Issuer agent)
  end

  subgraph TB_Registry["TB-04 Registry / status control"]
    DS_VDR[(DS-02<br/>Registry /<br/>status data)]
  end

  EE_Issuer ~~~ PO_IssuerAgent
  PO_IssuerAgent ~~~ PO_Browser
  PO_Browser ~~~ DS_VDR
  PO_Browser ~~~ PO_VerifierAgent
  PO_VerifierAgent ~~~ EE_Verifier
  EE_Holder ~~~ PO_Browser

  EE_Issuer <==>|DF-01<br/>Issuance decision<br/>and claims| PO_IssuerAgent
  PO_IssuerAgent ==>|DF-07<br/>Status or<br/>revocation update| DS_VDR
  PO_Wallet <==>|DF-03<br/>Store / retrieval<br/>credential| DS_CredentialRepo
  EE_Holder <==>|DF-04<br/>User decision<br/>/ action| PO_Browser
  PO_IssuerAgent <==>|DF-02<br/>Credential issuing| PO_Browser
  PO_Browser <==>|DF-08<br/>Credential request<br/>/ presentation| PO_VerifierAgent
  PO_Browser <==>|DF-09<br/>Browser<br/>mediation| PO_Wallet
  DS_VDR <==>|DF-05<br/>Verification material<br/>and status exchange| PO_VerifierAgent
  PO_VerifierAgent <==>|DF-06<br/>Verification and<br/>policy result| EE_Verifier

  classDef default fill:#fff,stroke:#000,stroke-width:4px,color:#000,font-size:22px,font-weight:bold,font-family:Arial
  linkStyle default stroke:#000,stroke-width:3px,color:#000
  linkStyle 0,1,2,3,4,5 stroke:#fff,stroke-width:0px,color:#fff
  style TB_Holder stroke-dasharray: 8 6,stroke:#000,stroke-width:4px,fill:#fff,color:#000
  style TB_Issuer stroke-dasharray: 8 6,stroke:#000,stroke-width:4px,fill:#fff,color:#000
  style TB_Verifier stroke-dasharray: 8 6,stroke:#000,stroke-width:4px,fill:#fff,color:#000
  style TB_Registry stroke-dasharray: 8 6,stroke:#000,stroke-width:4px,fill:#fff,color:#000
